export const products = [
  { id: 'story', name: 'Sayhi Story', word: 'STORY', number: '01', image: `${import.meta.env.BASE_URL}assets/story-world.png`, color: '#e8ac67', zh: { label: '故事', title: '一个念头，\n万千可能。', description: '让文字成为想象的起点。让每一个值得被看见的故事，找到跨越语言与地域的读者。', tag: '故事的起点', format: '短篇故事 · 全球阅读', detail: '从一段灵感，到完整的故事。Sayhi Story 聚焦内容与创作者，让富有生命力的文字走向更广阔的舞台。', scene: '云海之上', caption: '当最后一座城浮出云海，她终于听见了那个消失已久的名字。' }, en: { label: 'Stories', title: 'One idea.\nEndless possibilities.', description: 'Every world begins with a few words. A home for stories that deserve to be discovered, across languages and borders.', tag: 'WHERE IT ALL BEGINS', format: 'Short fiction · Global reading', detail: 'From the first spark to the final chapter. Sayhi Story connects imaginative storytelling with a wider world of readers.', scene: 'Above the Clouds', caption: 'As the last city rose from the clouds, she heard the name the world had forgotten.' } },
  { id: 'tv', name: 'Sayhi TV', word: 'TV', number: '02', image: `${import.meta.env.BASE_URL}assets/tv-world.png`, color: '#e46462', zh: { label: '剧集', title: '好故事，\n不止于观看。', description: '让文字走进镜头，让观众走进剧情。探索短剧与互动叙事，让每一次选择开启新的可能。', tag: '让故事跃上银幕', format: '短剧 · 互动叙事 · 多端体验', detail: 'Sayhi TV 面向全球观众探索短剧与互动剧集。故事从屏幕出发，在不同语言、文化与观看场景中找到共鸣。', scene: '雨夜来信', caption: '午夜零点，一封没有署名的信，让她再次走进这座城市的秘密。' }, en: { label: 'Series', title: 'Beyond watching.\nInto the story.', description: 'Bring words to the screen and audiences into the action. Explore short-form drama and the possibilities of interactive storytelling.', tag: 'STORIES IN MOTION', format: 'Short drama · Interactive stories', detail: 'Sayhi TV explores short-form and interactive drama for global audiences, bringing stories to life across languages, cultures, and screens.', scene: 'Midnight Letter', caption: 'At midnight, an unsigned letter draws her back into the secrets of the city.' } },
  { id: 'meta', name: 'Sayhi Meta', word: 'META', number: '03', image: `${import.meta.env.BASE_URL}assets/portal-scene.png`, color: '#ff684b', zh: { label: '世界', title: '想象的边界，\n由你打开。', description: '从文字中生长出世界。从读一个故事、看一段剧情，到走进一个可以探索的想象空间。', tag: '跨过想象的边界', format: '文生世界 · 沉浸探索', detail: 'Sayhi Meta 探索文生世界的可能，让叙事向空间延伸，让创意成为可以进入的世界。这里呈现的是品牌概念体验。', scene: '门后的世界', caption: '推开那扇门，故事不再只存在于想象之中。' }, en: { label: 'Worlds', title: 'Open the door\nto your imagination.', description: 'Worlds unfolding from words. Go beyond reading and watching, and step inside a space shaped by imagination.', tag: 'BEYOND THE FRAME', format: 'Text to world · Immersive exploration', detail: 'Sayhi Meta explores text-to-world experiences, extending stories into spaces. This website presents a visual brand concept.', scene: 'Beyond the Door', caption: 'Step through the door. The story no longer lives only in your imagination.' } },
];

export const copy = {
  zh: {
    nav: ['我们的世界', '产品', 'IP 宇宙'], explore: '开启探索', hero: ['每一个故事，', '都是一个世界。'], intro: '以东方创意，连接全球想象。\n在这里，AI 让故事跨越边界，生长为更大的世界。', side: '想象，在此成真。', scroll: '向下，发现更多', aboutLabel: '关于四海', aboutTitle: ['故事没有边界。', '想象，自有四海。'], aboutText: '我们相信，一个好故事的生命力，远不止于纸面。中文四海连接内容、技术与 IP，让文字成为影像，让角色走进生活，让东方创意与全球观众相遇。', productLabel: '我们的产品', productTitle: '一个故事的三种可能。', productIntro: '从阅读，到观看，再到身临其境。', preview: '探索这个世界', concept: '概念视觉', next: '下一个世界', toolsLabel: '创作的力量', toolsTitle: ['灵感在人。', '可能，在 AI。'], toolsIntro: '让技术服务于表达，让创作者专注于创造。', tools: [ ['Hi-story AI', '从灵感到故事', '辅助构思与剧本创作，让故事的第一步，更进一步。'], ['Hi-TV AI', '从故事到影像', '探索 AI 影像创作，让文字拥有镜头语言。'], ['Hi-Meta AI', '从文字到世界', '探索文生世界，让想象拥有更丰富的维度。'] ], ipLabel: '四海 IP 宇宙', ipTitle: ['不止一个角色。', '一种鲜明的态度。'], ipText: '火焰般的想象力，无拘束的创造力。\n从一个故事出发，让角色成为被记住的存在。', poses: ['正面', '侧面', '背面'], ipHint: '拖拽旋转 · 滚轮缩放', ipCaption: '红哪吒 · SAYHI 品牌吉祥物', footerLabel: '下一个世界，从一个好故事开始。', footerTitle: ['向世界，', '说声 Hi。'], footerAction: '再次探索', pause: '暂停动态效果', resume: '开启动态效果', close: '关闭预览', modalLabel: '产品概念预览', modalNote: '此画面为官网概念演示，非已上线产品或真实剧集片段。', closeMenu: '关闭菜单', menu: '打开菜单', back: '返回顶部', footerNote: '品牌官网概念演示',
  },
  en: {
    nav: ['Our world', 'Products', 'IP universe'], explore: 'Enter our world', hero: ['Every story.', 'A whole new world.'], intro: 'Chinese creativity. Global imagination.\nWith AI, stories cross borders and become something greater.', side: 'IMAGINATION, MADE REAL.', scroll: 'SCROLL TO DISCOVER', aboutLabel: 'ABOUT SAYHI', aboutTitle: ['Stories without borders.', 'Imagination without limits.'], aboutText: 'We believe a great story has a life beyond the page. Sayhi brings content, technology, and IP together — turning words into moving images and characters into lasting connections.', productLabel: 'OUR PRODUCTS', productTitle: 'One story. Three possibilities.', productIntro: 'Read it. Watch it. Step inside it.', preview: 'Explore this world', concept: 'CONCEPT ART', next: 'Next world', toolsLabel: 'THE POWER TO CREATE', toolsTitle: ['Human imagination.', 'AI possibilities.'], toolsIntro: 'Technology in service of expression. More room to create.', tools: [ ['Hi-story AI', 'From spark to story', 'Supporting ideas and scriptwriting, from the first thought to the next chapter.'], ['Hi-TV AI', 'From story to screen', 'Exploring AI-powered visual creation to give words a cinematic language.'], ['Hi-Meta AI', 'From words to worlds', 'Exploring text-to-world creation and new dimensions of imagination.'] ], ipLabel: 'THE SAYHI IP UNIVERSE', ipTitle: ['More than a character.', 'An unmistakable attitude.'], ipText: 'An imagination on fire. A spirit without limits.\nFrom the heart of a story to a character you remember.', poses: ['Front', 'Side', 'Back'], ipHint: 'DRAG TO ROTATE · SCROLL TO ZOOM', ipCaption: 'RED NEZHA · SAYHI BRAND MASCOT', footerLabel: 'Every new world begins with a great story.', footerTitle: ['A world of stories.', 'Say hi.'], footerAction: 'Explore again', pause: 'Pause motion', resume: 'Enable motion', close: 'Close preview', modalLabel: 'PRODUCT CONCEPT PREVIEW', modalNote: 'A visual concept for this website, not a live product or an actual series clip.', closeMenu: 'Close menu', menu: 'Open menu', back: 'Back to top', footerNote: 'BRAND WEBSITE CONCEPT',
  },
};
